# Фундаментальные концепции ИИ

## Лабораторная работа №2
### Глобальная оптимизация и метаэвристические алгоритмы

Выполнил студент группы М8О-109СВ-24 Кучев Антон

In [7]:
import pygmo as pg
#import sympy as sy
import pandas as pd
import numpy as np
print(pg.__version__)

2.19.7


Создаём класс для функции Бута

In [8]:
class booth_expr:
    def fitness(self, x):
        func = (x[0] + 2 * x[1] - 7)**2 + (2 * x[0] + x[1] - 5)**2
        return [func]
    
    def get_bounds(self):
        return ([-10, -10], [10, 10])


Создадим объект класса problem на основе функции Бута

In [9]:
prob = pg.problem(booth_expr())

In [10]:
prob

Problem name: <class '__main__.booth_expr'>
	C++ class name: class pybind11::object

	Global dimension:			2
	Integer dimension:			0
	Fitness dimension:			1
	Number of objectives:			1
	Equality constraints dimension:		0
	Inequality constraints dimension:	0
	Lower bounds: [-10, -10]
	Upper bounds: [10, 10]
	Has batch fitness evaluation: false

	Has gradient: false
	User implemented gradient sparsity: false
	Has hessians: false
	User implemented hessians sparsity: false

	Fitness evaluations: 0

	Thread safety: none

Создадим архипелаг, на котором будет 16 островов, на каждом острове будет использоваться алгоритм пчелиного роя, размер популяции - 100

In [35]:
archi = pg.archipelago(n = 16, algo = pg.bee_colony(gen = 50, limit = 10), prob = prob, pop_size = 100, seed = 32)
archi.evolve()

In [36]:
archi.wait()
res_bees = archi.get_champions_f()
res_bees

[array([0.00126402]),
 array([0.00013454]),
 array([0.00104498]),
 array([6.91586804e-05]),
 array([0.00159553]),
 array([5.77798706e-05]),
 array([4.61755013e-05]),
 array([0.00087278]),
 array([6.34771085e-06]),
 array([0.00142806]),
 array([0.00012232]),
 array([0.0001738]),
 array([6.63774391e-06]),
 array([0.0004635]),
 array([0.00038389]),
 array([7.56722056e-05])]

То же самое для алгоритма Grey Wolf Optimizer

In [39]:
archi = pg.archipelago(n = 16, algo = pg.gwo(gen = 50), prob = prob, pop_size = 100, seed = 32)
archi.evolve()

In [40]:
archi.wait()
res_wolfs = archi.get_champions_f()
res_wolfs

[array([8.81128868e-06]),
 array([2.74949306e-06]),
 array([1.58307159e-06]),
 array([7.22869299e-06]),
 array([3.79981306e-09]),
 array([2.78086026e-07]),
 array([1.41949231e-06]),
 array([4.60163968e-10]),
 array([2.82759534e-06]),
 array([1.34826422e-05]),
 array([3.69509013e-06]),
 array([1.51490732e-05]),
 array([1.01878446e-06]),
 array([6.0889925e-07]),
 array([5.41459776e-06]),
 array([6.23269581e-06])]

Импользуем также алгоритм имитации отжига

In [43]:
archi = pg.archipelago(n = 16, algo = pg.simulated_annealing(Ts=100., Tf=.1, n_T_adj=50, n_range_adj=50), prob = prob, pop_size = 100, seed = 32)
archi.evolve()

In [44]:
archi.wait()
res_annealing = archi.get_champions_f()
res_annealing

[array([6.14665649e-08]),
 array([1.70345054e-05]),
 array([6.14665649e-08]),
 array([1.70345054e-05]),
 array([6.14665649e-08]),
 array([6.14665649e-08]),
 array([6.14665649e-08]),
 array([6.14665649e-08]),
 array([6.14665649e-08]),
 array([6.14665649e-08]),
 array([6.14665649e-08]),
 array([6.14665649e-08]),
 array([1.70345054e-05]),
 array([1.70345054e-05]),
 array([6.14665649e-08]),
 array([6.14665649e-08])]

Занесём данные в pandas dataframe

In [45]:
res_wolfs = [res_wolfs[i][0] for i in range(len(res_wolfs))]
res_bees = [res_bees[i][0] for i in range(len(res_bees))]
res_annealing = [res_annealing[i][0] for i in range(len(res_annealing))]

In [46]:
data = {'Real min value' : np.zeros(len(res_wolfs)) ,
         'Bee colony absolute erroe' : res_bees,
         'Grey Wolf Optimizer absolute error' : res_wolfs,
         'Simulated Annealing absolute error' : res_annealing}

compare_booth = pd.DataFrame(data=data)

In [34]:
compare_booth

Real min value  Bee colony absolute erroe  \
0              0.0                   0.000110   
1              0.0                   0.002593   
2              0.0                   0.001159   
3              0.0                   0.000533   
4              0.0                   0.000671   
5              0.0                   0.000177   
6              0.0                   0.000002   
7              0.0                   0.000522   
8              0.0                   0.000052   
9              0.0                   0.000384   
10             0.0                   0.000344   
11             0.0                   0.000369   
12             0.0                   0.000490   
13             0.0                   0.000181   
14             0.0                   0.000298   
15             0.0                   0.000401   

    Grey Wolf Optimizer absolute error  Simulated Annealing absolute error  
0                         4.511178e-06                            0.000004  
1                         3.946110e-06                            0.000004  
2                         2.144247e-07                            0.000004  
3                         1.072206e-05                            0.000004  
4                         7.764650e-06                            0.000027  
5                         4.229339e-07                            0.000004  
6                         8.402780e-06                            0.000031  
7                         9.413065e-07                            0.000004  
8                         1.090378e-05                            0.000004  
9                         6.687791e-07                            0.000004  
10                        2.834339e-07                            0.000027  
11                        1.540677e-05                            0.000004  
12                        3.181904e-06                            0.000004  
13                        4.989086e-07                            0.000027  
14                        1.391714e-05                            0.000027  
15                        6.540808e-07                            0.000027

In [65]:
class shaffer_expr:
    def fitness(self, x):
        func = 0.5 + (np.cos(np.sin(np.abs(x[0]**2 - x[1]**2)))**2 - 0.5) / (1 + 0.001 * (x[0]**2 + x[1]**2))**2
        return [func]
    
    def get_bounds(self):
        return ([-100, -100], [100, 100])


In [66]:
prob = pg.problem(shaffer_expr())

In [67]:
prob

Problem name: <class '__main__.shaffer_expr'>
	C++ class name: class pybind11::object

	Global dimension:			2
	Integer dimension:			0
	Fitness dimension:			1
	Number of objectives:			1
	Equality constraints dimension:		0
	Inequality constraints dimension:	0
	Lower bounds: [-100, -100]
	Upper bounds: [100, 100]
	Has batch fitness evaluation: false

	Has gradient: false
	User implemented gradient sparsity: false
	Has hessians: false
	User implemented hessians sparsity: false

	Fitness evaluations: 0

	Thread safety: none

In [68]:
archi = pg.archipelago(n = 16, algo = pg.bee_colony(gen = 50, limit = 10), prob = prob, pop_size = 100, seed = 32)
archi.evolve()

In [69]:
archi

Number of islands: 16
Topology: Unconnected
Migration type: point-to-point
Migrant handling policy: preserve
Status: idle

Islands summaries:

	#   Type                    Algo                        Prob                             Size  Status  
	-------------------------------------------------------------------------------------------------------
	0   Multiprocessing island  ABC: Artificial Bee Colony  <class '__main__.shaffer_expr'>  100   idle    
	1   Multiprocessing island  ABC: Artificial Bee Colony  <class '__main__.shaffer_expr'>  100   idle    
	2   Multiprocessing island  ABC: Artificial Bee Colony  <class '__main__.shaffer_expr'>  100   idle    
	3   Multiprocessing island  ABC: Artificial Bee Colony  <class '__main__.shaffer_expr'>  100   idle    
	4   Multiprocessing island  ABC: Artificial Bee Colony  <class '__main__.shaffer_expr'>  100   idle    
	5   Multiprocessing island  ABC: Artificial Bee Colony  <class '__main__.shaffer_expr'>  100   idle    
	6   Multiprocess

In [70]:
archi.wait()
res_bees = archi.get_champions_f()
res_bees

[array([0.29318555]),
 array([0.29270513]),
 array([0.29335253]),
 array([0.29270009]),
 array([0.29268281]),
 array([0.29259056]),
 array([0.29263347]),
 array([0.29297393]),
 array([0.29262125]),
 array([0.29307929]),
 array([0.29260263]),
 array([0.29298704]),
 array([0.29259247]),
 array([0.29265479]),
 array([0.29264737]),
 array([0.29260363])]

In [71]:
archi = pg.archipelago(n = 16, algo = pg.gwo(gen = 50), prob = prob, pop_size = 100, seed = 32)
archi.evolve()

In [72]:
archi

Number of islands: 16
Topology: Unconnected
Migration type: point-to-point
Migrant handling policy: preserve
Status: idle

Islands summaries:

	#   Type                    Algo                      Prob                             Size  Status  
	-----------------------------------------------------------------------------------------------------
	0   Multiprocessing island  GWO: Grey Wolf Optimizer  <class '__main__.shaffer_expr'>  100   idle    
	1   Multiprocessing island  GWO: Grey Wolf Optimizer  <class '__main__.shaffer_expr'>  100   idle    
	2   Multiprocessing island  GWO: Grey Wolf Optimizer  <class '__main__.shaffer_expr'>  100   idle    
	3   Multiprocessing island  GWO: Grey Wolf Optimizer  <class '__main__.shaffer_expr'>  100   idle    
	4   Multiprocessing island  GWO: Grey Wolf Optimizer  <class '__main__.shaffer_expr'>  100   idle    
	5   Multiprocessing island  GWO: Grey Wolf Optimizer  <class '__main__.shaffer_expr'>  100   idle    
	6   Multiprocessing island  GWO:

In [73]:
archi.wait()
res_wolfs = archi.get_champions_f()
res_wolfs 

[array([0.29258279]),
 array([0.29258447]),
 array([0.29259285]),
 array([0.29260492]),
 array([0.29257863]),
 array([0.29257936]),
 array([0.29257872]),
 array([0.29258053]),
 array([0.29257955]),
 array([0.29264279]),
 array([0.29258453]),
 array([0.29263522]),
 array([0.29258378]),
 array([0.29257964]),
 array([0.29258818]),
 array([0.29258174])]

In [84]:
archi = pg.archipelago(n = 16, algo = pg.simulated_annealing(Ts=100., Tf=.1, n_T_adj=50, n_range_adj=50), prob = prob, pop_size = 100, seed = 32)
archi.evolve()

In [85]:
archi.wait()
res_annealing = archi.get_champions_f()
res_annealing

[array([0.29357301]),
 array([0.29357301]),
 array([0.29357301]),
 array([0.29357301]),
 array([0.29357301]),
 array([0.29357301]),
 array([0.29357301]),
 array([0.29357301]),
 array([0.29357301]),
 array([0.29357301]),
 array([0.29357301]),
 array([0.29357301]),
 array([0.29357301]),
 array([0.29357301]),
 array([0.29357301]),
 array([0.29357301])]

In [86]:
real_val = np.ones(len(res_wolfs)) * 0.292579
res_wolfs = [res_wolfs[i][0] for i in range(len(res_wolfs))]
res_bees = [res_bees[i][0] for i in range(len(res_bees))]
res_annealing = [res_annealing[i][0] for i in range(len(res_annealing))]

In [87]:
real_val = np.ones(len(res_wolfs)) * 0.292579

data = {'Real min value' : real_val,
         'Bee colony result' : res_bees, 'Bee colony absolute error' : np.abs(res_bees - real_val),
         'Grey Wolf Optimizer result' : res_wolfs, 'Grey Wolf Optimizer absolute error' : np.abs(res_wolfs - real_val),
         'Simulated Annealing result' : res_annealing, 'Simulated Annealing absolut error' : np.abs(res_annealing - real_val)}

compare_shaffer = pd.DataFrame(data=data)

In [88]:
compare_shaffer

Real min value  Bee colony result  Bee colony absolute error  \
0         0.292579           0.293186                   0.000607   
1         0.292579           0.292705                   0.000126   
2         0.292579           0.293353                   0.000774   
3         0.292579           0.292700                   0.000121   
4         0.292579           0.292683                   0.000104   
5         0.292579           0.292591                   0.000012   
6         0.292579           0.292633                   0.000054   
7         0.292579           0.292974                   0.000395   
8         0.292579           0.292621                   0.000042   
9         0.292579           0.293079                   0.000500   
10        0.292579           0.292603                   0.000024   
11        0.292579           0.292987                   0.000408   
12        0.292579           0.292592                   0.000013   
13        0.292579           0.292655                   0.000076   
14        0.292579           0.292647                   0.000068   
15        0.292579           0.292604                   0.000025   

    Grey Wolf Optimizer result  Grey Wolf Optimizer absolute error  \
0                     0.292583                        3.789547e-06   
1                     0.292584                        5.472586e-06   
2                     0.292593                        1.385113e-05   
3                     0.292605                        2.591926e-05   
4                     0.292579                        3.667707e-07   
5                     0.292579                        3.606794e-07   
6                     0.292579                        2.803733e-07   
7                     0.292581                        1.526853e-06   
8                     0.292580                        5.497261e-07   
9                     0.292643                        6.379498e-05   
10                    0.292585                        5.533921e-06   
11                    0.292635                        5.621749e-05   
12                    0.292584                        4.775639e-06   
13                    0.292580                        6.377325e-07   
14                    0.292588                        9.184412e-06   
15                    0.292582                        2.740275e-06   

    Simulated Annealing result  Simulated Annealing absolut error  
0                     0.293573                           0.000994  
1                     0.293573                           0.000994  
2                     0.293573                           0.000994  
3                     0.293573                           0.000994  
4                     0.293573                           0.000994  
5                     0.293573                           0.000994  
6                     0.293573                           0.000994  
7                     0.293573                           0.000994  
8                     0.293573                           0.000994  
9                     0.293573                           0.000994  
10                    0.293573                           0.000994  
11                    0.293573                           0.000994  
12                    0.293573                           0.000994  
13                    0.293573                           0.000994  
14                    0.293573                           0.000994  
15                    0.293573                           0.000994